- hosts: localhost
  vars:
    - config: "{{ playbook_dir }}/config.json"
    - ov_template:  Ansible-DL380Gen10 
    - profile_name: "DL380Gen10-ServerProfile"
    - server_hardware: "serverhardware"
  tasks:
    - name: Create a Server Profile from a Server Profile Template
      oneview_server_profile:
        config: "{{ config }}"
        auto_assign_server_hardware: True
        data:
          serverProfileTemplateName: "{{ ov_template }}"
          name: "{{ profile_name }}"
          serverHardwareName: "{{ server_hardware }}"
        
        params: # Supported only in API version >= 600
          force: True
      delegate_to: localhost
      register: result

    - debug: msg="{{ result.msg }}"
